basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:hosting_id>/', basketapp.add, name='add'),
    path('remove/<int:hosting_basket_id>/', basketapp.remove, name='remove'),
]

kpk/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.conf.urls.static import static

import mainapp.views as mainapp
from django.urls import path
from kpk import settings

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),

    # path('catalog/', mainapp.catalog, name='catalog'),
    path('catalog/', mainapp.CatalogListView.as_view(), name='catalog'),

    path('catalog/<int:category_pk>/', mainapp.catalog_page, name='catalog_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.contrib.auth.models import User
from django.db import models

from mainapp.models import Hosting


class HostingBasket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hosting = models.ForeignKey(Hosting, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.hosting.name}'

basketapp/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse

from basketapp.models import HostingBasket
from mainapp.models import Hosting


def index(request):
    items = HostingBasket.objects.filter(user=request.user)
    context = {
        'object_list': items,
    }
    return render(request, 'basketapp/basket.html', context)


def add(request, hosting_id):
    hosting = Hosting.objects.get(pk=hosting_id)
    HostingBasket.objects.get_or_create(
        user=request.user,
        hosting=hosting
    )
    return HttpResponseRedirect(
        reverse('mainapp:catalog_page', kwargs={'category_pk': hosting.category_id})
    )


def remove(request, hosting_basket_id):
    if request.is_ajax():
        hosting = HostingBasket.objects.get(id=hosting_basket_id)
        hosting.delete()
        return JsonResponse({
            'status': 'true',
            'text': hosting_basket_id,
        })

basketapp/templates/basketapp/basket.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    <title>Корзина</title>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <div class="card">
            <div class="card-body text-center">
                {% if object_list %}
                    <h3 class="bg-inverse text-success">Ваш заказ:</h3>
                    <div class="row">
                        {% for item in object_list %}
                            <div class="col"><h3>{{ item }}</h3> <a href="{% url 'basket:remove' item.pk %}"
                                                                    class="btn btn-outline-danger basket_remove">удалить</a>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="container-show">
                        <a class="p-2 text-dark" href="{% url 'main:catalog' %}"><i class="fas fa-shopping-basket"></i>Перейти
                            в каталог</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}