authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
        path('login/', authapp.login, name='login'),
        path('logout/', authapp.logout, name='logout'),
        path('register/', authapp.register, name='register'),
        path('profile/', authapp.profile, name='profile'),
        path('profile/edit_profile', authapp.edit_profile, name='edit_profile'),
]

basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:hosting_id>/', basketapp.add, name='add'),
    path('remove/<int:hosting_basket_id>/', basketapp.remove, name='remove'),
]

kpk/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.conf.urls.static import static

import mainapp.views as mainapp
from django.urls import path
from kpk import settings

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),

    # path('catalog/', mainapp.catalog, name='catalog'),
    path('catalog/', mainapp.CatalogListView.as_view(), name='catalog'),

    path('catalog/<int:category_pk>/', mainapp.catalog_page, name='catalog_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from django.contrib.auth.models import User
from django.db import models


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField(verbose_name='возраст', null=True)
    about = models.TextField(verbose_name='Обо мне', blank=True)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'пользователя'
        verbose_name_plural = 'пользователи'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
import django.forms as forms
from authapp.models import UserProfile


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'password1',
            'password2',
            'email',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

    def save(self, commit=True):
        user = super().save(commit=commit)
        UserProfile.objects.create(user=user)
        return user


class ChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''
            if name == 'password':
                item.widget = forms.HiddenInput()

    def save(self, commit=True):
        user = super().save(commit=commit)
        user.userprofile.save()
        return user

authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from authapp.forms import LoginForm, RegisterForm, ChangeForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = LoginForm()
    content = {
        'page_title': 'Авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegisterForm()
    content = {
        'page_title': 'Регистрация',
        'form': form,
    }
    return render(request, 'authapp/register.html', content)


def profile(request):
    context = {
        'page_title': 'Профиль',
    }
    return render(request, 'authapp/profile.html', context)


def edit_profile(request):
    if request.method == 'POST':
        form = ChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            if request.is_ajax():
                form.save()
                return HttpResponseRedirect(reverse('authapp:edit_profile'))
    else:
        form = ChangeForm(instance=request.user)

    context = {
        'page_title': 'редактирование',
        'form': form,
    }
    return render(request, 'authapp/edit.html', context)

authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap-material-design.min.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
          integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="/static/img/favicon.png"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/notyf.min.css' %}">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a class="p-2 text-dark" href="/">BIGNETHOST</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'main:index' %}">Главная</a>
        <a class="p-2 text-dark" href="{% url 'main:catalog' %}"><i class="fas fa-shopping-basket"></i>Каталог</a>
        <a class="p-2 text-dark" href="{% url 'basketapp:index' %}"><i class="fas fa-shopping-cart"></i>Корзина</a>
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'authapp:logout' %}"><i class="fas fa-sign-in-alt"></i>Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'authapp:login' %}"><i class="fas fa-sign-in-alt"></i>Войти</a>
        {% endif %}
    </nav>

</div>
{% block content %}
{% endblock %}
<br>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap-material-design.js' %}"></script>
<script src="{% static 'js/notyf.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('body').bootstrapMaterialDesign();
    });
    let notyf;
    notyf = new Notyf({
        duration: 2000,
        position: {
            x: 'right',
            y: 'top',
        },
    });
    $(".edit").click(function () {
        notyf.error('Пока что изменить данные нельзя!')
    });
</script>
</body>
</html>

authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}
    <div class="container">
        <h3 class="text-center mb-5">Редактирование</h3>
        <div class="container">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit"
                       class="btn btn-success btn-block"
                       value="сохранить">
                <a class="btn btn-info btn-block" href="{% url 'main:index' %}">Главная</a>
            </form>

        </div>
    </div>
{% endblock %}

authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}
    <div class="container">
        <h3 class="text-center mb-5">Авторизация</h3>
        <form class="p-lg-3" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" class="btn btn-outline-success float-right login" value="Войти"/>
            <p><a class="btn btn-outline-warning float-left" href="{% url 'auth:register' %}">Зарегистрироваться</a></p>
        </form>

    </div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}
    <div class="container">
        <h3 class="text-center mb-5">Профиль</h3>
        <div class="container">
            <div class="row">
                <div class="col">
                    <span class="input-group-text">Имя пользователя</span>
                    <input type="text" class="form-control" id="first_name" value="{{ user.first_name }}" readonly>
                    <span class="input-group-text">Логин</span>
                    <input type="text" class="form-control" id="username" value="{{ user.username }}" readonly>
                </div>
                <div class="col text-center">
                    <span class="input-group-text">Почта</span>
                    <input type="text" class="form-control" id="email" value="{{ user.email }}" readonly>
                </div>
            </div>
            <br>
            <a href="{% url 'auth:edit_profile' %}" class="btn btn-outline-success float-right edit">Изменить</a>
        </div>
    </div>
{% endblock %}
<script>

</script>

authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
<title>{{ page_title|capfirst }}</title>
{% block content %}
    <div class="container">
        <h3 class="text-center mb-5">Регистрация</h3>
        <form class="p-lg-3" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" class="btn btn-outline-primary btn-block" value="Зарегистрироваться"/>
        </form>
    </div>
{% endblock %}