authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
        path('login/', authapp.login, name='login'),
        path('logout/', authapp.logout, name='logout'),
        path('register/', authapp.register, name='register'),
        path('profile/', authapp.profile, name='profile'),
        path('profile/edit_profile', authapp.edit_profile, name='edit_profile'),
]

basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:hosting_id>/', basketapp.add, name='add'),
    path('remove/<int:hosting_basket_id>/', basketapp.remove, name='remove'),
]

kpk/urls.py
import mainapp.views as mainapp
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('mainapp.urls', namespace='main')),

    path('auth/', include('authapp.urls', namespace='auth')),

    path('basket/', include('basketapp.urls', namespace='basket')),

    path('admin/', admin.site.urls),
]

mainapp/urls.py
from django.conf.urls.static import static

import mainapp.views as mainapp
from django.urls import path
from kpk import settings

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),

    # path('catalog/', mainapp.catalog, name='catalog'),
    path('catalog/', mainapp.CatalogListView.as_view(), name='catalog'),

    path('catalog/<int:category_pk>/', mainapp.catalog_page, name='catalog_page'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField('Название категории', max_length=128)
    image = models.ImageField('Картинка', upload_to='category', height_field=None, width_field=None, max_length=100,
                              null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'


class Hosting(models.Model):
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название тарифа', max_length=128)
    desc = models.TextField(verbose_name='Описание тарифа', blank=True)
    prise = models.IntegerField(verbose_name='Цена', default=0)
    disk = models.CharField(verbose_name='Дисковое пространство', max_length=128)
    site = models.CharField(verbose_name='Сайты', max_length=128, blank=True)
    db = models.CharField(verbose_name='База Данных', max_length=128, blank=True)
    cpu = models.CharField(verbose_name='Нагрузка на цп', max_length=128)
    ram = models.CharField(verbose_name='Оперативная память', max_length=128, blank=True)
    traffic = models.CharField(verbose_name='Трафик', max_length=128)
    location = models.CharField(verbose_name='Локация', max_length=128)
    ddos = models.CharField(verbose_name='Защита от ДДОС', max_length=128)
    is_active = models.BooleanField(verbose_name='Активный тариф')
    image = models.ImageField(verbose_name='Картинка', upload_to='hosting', height_field=None, width_field=None, max_length=100,
                              null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'хостинг'
        verbose_name_plural = 'хостинги'

mainapp/views.py
from django.shortcuts import render
from django.views.generic import ListView

from mainapp.models import Category, Hosting


class PageTitleMixin:
    page_title = ''

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['page_title'] = self.page_title
        return context


def index(request):
    context = {
        'page_title': 'главная',
    }
    return render(request, 'mainapp/index.html', context)


class CatalogListView(PageTitleMixin, ListView):
    model = Category
    page_title = 'каталог'

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(object_list=object_list, **kwargs)
    #     context['page_title'] = 'каталог'
    #     return context


def catalog_page(request, category_pk):
    hosting = Hosting.objects.filter(category_id=category_pk)
    context = {
        'page_title': 'страница услуг',
        'hosting': hosting,
    }
    return render(request, 'mainapp/catalog_page.html', context)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap-material-design.min.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css"
          integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png" href="/static/img/favicon.png"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/notyf.min.css' %}">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a class="p-2 text-dark" href="/">BIGNETHOST</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'main:index' %}">Главная</a>
        <a class="p-2 text-dark" href="{% url 'main:catalog' %}"><i class="fas fa-shopping-basket"></i>Каталог</a>
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'basketapp:index' %}"><i class="fas fa-shopping-cart"></i>Корзина</a>
            <button class="btn btn-secondary dropdown-toggle text-dark" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {% if user.is_superuser %}
                    <i class="fa fa-chess-king">{{ user.username }}</i>
                {% else %}
                    <i class="fa fa-user">{{ user.username }}</i>
                {% endif %}
            </button>
            <div class="dropdown-menu text-dark" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'auth:edit_profile' %}"><i
                        class="fas fa-dice-d6 text-danger"></i>{{ user.first_name }}</a>
                <a class="dropdown-item" href="{% url 'auth:logout' %}"><i class="fas fa-sign-in-alt"></i>Выйти</a>
            </div>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'auth:login' %}"><i class="fas fa-sign-in-alt"></i>Войти</a>
            <a class="p-2 text-dark" href="{% url 'auth:register' %}"><i
                    class="fas fa-user-check"></i>Регистрация</a>

        {% endif %}
    </nav>

</div>
{% block content %}
{% endblock %}
<br>
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap-material-design.js' %}"></script>
<script>
    $(document).ready(function () {
        $('body').bootstrapMaterialDesign();
    });
</script>
<script src="{% static 'js/notyf.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

mainapp/templates/mainapp/basket.html
{% extends 'mainapp/base.html' %}
{% block title %}
    <title>Корзина</title>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <div class="card">
            <div class="card-body text-center">
                <h1>Пусто</h1>
                <a class="p-2 text-dark" href="{% url 'mainapp:catalog' %}"><i class="fas fa-shopping-basket"></i>Перейти в каталог</a>
            </div>
        </div>
    </div>

{% endblock %}

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <style>
        a, a:hover {
            text-decoration: #212529;
            color: #212529;
        }
    </style>
    <div class="container">
        <br>
        {% for item in categories %}
            <div class="card-deck">
                <a href="{% url 'main:catalog_page' item.pk %}" class="card-title text-center">
                    <div class="card">
                        <img class="card-img-top" src="{{ item.image.url }}" alt="Card image cap">
                        <div class="card-body text-center">
                            <h3>

                                {{ item }}

                            </h3>
                        </div>
                    </div>
                </a>
            </div>
            <br>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/catalog_page.html
{% extends 'mainapp/base.html' %}
{% load static %}
    <title>Каталог</title>
{% block content %}

    <div class="container-fluid">
        <br>
        <a href="{% url 'main:catalog' %}">
            <button class="btn btn-outline-success"><i class="fas fa-arrow-left"></i>Назад</button>
        </a>
        <br>
        <div class="card-deck">
            {% for item in hosting %}
                {% if item.is_active %}
                    <div class="card">
                        <img class="card-img-top" src="{{ item.image.url }}" alt="Card image cap">
                        <div class="card-body text-center">
                            <h3 class="card-title text-center">{{ item.name }}</h3>
                            <table class="table">
                                <tbody>
                                <tr class="text-center">
                                    <th>NVMe диск: {{ item.disk }}</th>
                                </tr>
                                <tr class="text-center">
                                    <th>Сайт: {{ item.site }}</th>
                                </tr>
                                <tr class="text-center">
                                    <th>Базы данных: {{ item.db }}</th>
                                </tr>
                                <tr class="text-center">
                                    <th>% от ядра: {{ item.cpu }}</th>
                                </tr>
                                <tr class="text-center">
                                    <th>Трафик: {{ item.traffic }}</th>
                                </tr>
                                <tr class="text-center">
                                    <th>Локация: {{ item.location }}</th>
                                </tr>
                                <tr class="text-center">
                                    <th>Цена: {{ item.prise }} &#8381;/мес.</th>
                                </tr>
                                <tr class="text-center">
                                    <th>Защита от DDOS-Атак: {{ item.ddos }}</th>
                                </tr>
                                </tbody>
                            </table>
                            {% if user.is_authenticated %}
                                <a class="btn btn-success btn-block add"
                                   href="{% url 'basket:add' item.id %}">Заказать</a>
                            {% else %}
                                <a class="btn btn-success btn-block" href="{% url 'authapp:login' %}">Авторизоваться</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        <br>
    </div>
{% endblock %}

mainapp/templates/mainapp/category_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <style>
        a, a:hover {
            text-decoration: #212529;
            color: #212529;
        }
    </style>
    <div class="container">
        <br>
        {% for item in object_list %}
            <div class="card-deck">
                <a href="{% url 'main:catalog_page' item.pk %}" class="card-title text-center">
                    <div class="card">
                        <img class="card-img-top" src="{{ item.image.url }}" alt="Card image cap">
                        <div class="card-body text-center">
                            <h3>

                                {{ item }}

                            </h3>
                        </div>
                    </div>
                </a>
            </div>
            <br>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    <title>Главная</title>
{% endblock %}
{% block content %}
    <div class="container">
        <br>
        <h2 class="text-center mb-4">Облачные сервисы - решают любые задачи.</h2>
        <div class="row">
            <div class="card col">
                <img class="card-img-top" src="/static/img/cloud_hosting.png" alt="Card image cap">
                <div class="card-body text-center">
                    <h5 class="card-title text-center">Веб-хостинг</h5>
                    <p class="card-text">
                    <table class="table">
                        <tbody>
                        <tr class="text-center">
                            <th>Диск 30 GB</th>
                        </tr>
                        <tr class="text-center">
                            <th>Сайты &#8734;</th>
                        </tr>
                        <tr class="text-center">
                            <th>БД &#8734;</th>
                        </tr>
                        <tr class="text-center">
                            <th>Канал 500 Мбит/с</th>
                        </tr>
                        </tbody>
                    </table>
                    </p>
                    <a href="/catalog" class="btn btn-info">Смотреть тарифы</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}